# Generated by Django 3.0.5 on 2020-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('tag', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='Unknown Picture', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='hashtag',
            field=models.ManyToManyField(to='image.HashTag'),
        ),
    ]
