# Generated by Django 3.0.5 on 2020-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20200507_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='image.HashTag'),
        ),
    ]
